package assets;

public enum States
{
    BELOW_KARMAN,
    LAUNCH,
    BEYOND_KARMAN,
    RELEASE_PAYLOAD,
    LUNAR_ENTRY,
    POST_LUNAR_ENTRY,
    NEAR_LUNAR_SURFACE,
    MISSION_SUCCESFULL,
    MISSION_FAILED
}
